name: Actionsflow
on:
  # schedule:
  #   - cron: "*/15 * * * *"
  push:
    branches:
      - main
  repository_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '15'
        env:
          test_secret: ${{ secrets.test_secret }}

      - run: npm install
      - run: node index.js

